import "server-only";
import { createHash, randomUUID } from "node:crypto";
import type pg from "pg";
import type { CanonicalTaxReturnData } from "@/domain/canonical";
import { asDecimalString } from "@/domain/money";
import { authorize, type AuthorizationContext } from "@/services/authorization";
import type { Diagnostic } from "@/services/diagnostics";
import { exportCanonicalJson, type JsonExportMode } from "@/services/outputs/json-export-service";
import { generateDraftReturnPackage } from "@/services/outputs/return-package-service";
import { generateWorkpaper } from "@/services/outputs/workpaper-service";
import { WorkflowError } from "./client-workflow-service";
import { databasePool } from "./database";

export type ArtifactType = "return_package_pdf" | "workpaper_xlsx" | "complete_json" | "source_only_json" | "blank_template_json";
const artifactDefinitions: Record<ArtifactType,{mimeType:string;extension:string;templateVersion:string}>={
  return_package_pdf:{mimeType:"application/pdf",extension:"pdf",templateVersion:"draft-cover-v1"},
  workpaper_xlsx:{mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",extension:"xlsx",templateVersion:"workpaper-v1"},
  complete_json:{mimeType:"application/json",extension:"json",templateVersion:"canonical-json-v1"},
  source_only_json:{mimeType:"application/json",extension:"json",templateVersion:"canonical-json-v1"},
  blank_template_json:{mimeType:"application/json",extension:"json",templateVersion:"canonical-json-v1"},
};

export async function generatePersistedArtifact(context:AuthorizationContext,clientId:string,year:number,expectedRevision:number,artifactType:ArtifactType){
  return inTransaction(async client=>{
    const scope=await authorizedTaxYear(client,context,clientId,year,"output.generate",true);assertRevision(scope.revision,expectedRevision);
    if(artifactType==="complete_json"&&!authorize(context,"identifier.reveal",{firmId:context.firmId,clientId}))throw new WorkflowError("forbidden","Complete canonical export requires sensitive-identifier permission.");
    const runResult=await client.query<{id:string;input_revision:number;input_hash:string;engine_version:string;rule_version:string;form_registry_version:string;calculation_status:string;result:Record<string,any>;result_hash:string|null}>("SELECT id,input_revision,input_hash,engine_version,rule_version,form_registry_version,calculation_status,result,result_hash FROM calculation_runs WHERE tax_year_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE",[scope.taxYearId]);
    const run=runResult.rows[0];if(!run||run.input_revision!==scope.revision)throw new WorkflowError("conflict","A current persisted calculation run is required before generating outputs.");
    const definition=artifactDefinitions[artifactType];const idempotencyKey=createHash("sha256").update(JSON.stringify({taxYearId:scope.taxYearId,revision:scope.revision,runId:run.id,artifactType,templateVersion:definition.templateVersion,resultHash:run.result_hash})).digest("hex");
    const existing=await client.query<{id:string;artifact_status:string;content_hash:string|null}>("SELECT id,artifact_status,content_hash FROM generated_artifacts WHERE idempotency_key=$1",[idempotencyKey]);if(existing.rows[0])return{id:existing.rows[0].id,status:existing.rows[0].artifact_status,contentHash:existing.rows[0].content_hash,replayed:true};
    const data=await assembleCanonicalData(client,scope.taxYearId,clientId,year,scope.revision,context.firmId);
    const diagnostics=await readDiagnostics(client,scope.taxYearId);
    const requiredForms=requiredFormsForRun(run.result);
    const completeness="partial" as const;
    let bytes:Uint8Array;let serviceManifest:Record<string,unknown>={};
    if(artifactType==="return_package_pdf"){
      const generated=await generateDraftReturnPackage({taxYear:2025,inputRevision:scope.revision,calculationRunId:run.id,engineVersion:run.engine_version,ruleVersion:run.rule_version,requiredForms,renderedForms:[],missingForms:requiredForms,supportStatus:completeness});bytes=generated.bytes;serviceManifest={...generated.manifest};
    }else if(artifactType==="workpaper_xlsx")bytes=await generateWorkpaper({data,runId:run.id,calculationStatus:completeness,diagnostics});
    else{const mode:JsonExportMode=artifactType==="complete_json"?"complete":artifactType==="source_only_json"?"source_only":"blank_template";const generated=exportCanonicalJson(data,mode);bytes=generated.bytes;serviceManifest={mode:generated.mode,exclusions:generated.exclusions};}
    const contentHash=createHash("sha256").update(bytes).digest("hex");const artifactId=randomUUID();const fileName=`nexus-${year}-${artifactType.replaceAll("_","-")}-${run.id.slice(0,8)}.${definition.extension}`;
    const manifest={taxYear:year,inputRevision:scope.revision,calculationRunId:run.id,inputHash:run.input_hash,resultHash:run.result_hash,engineVersion:run.engine_version,ruleVersion:run.rule_version,formRegistryVersion:run.form_registry_version,templateVersion:definition.templateVersion,calculationStatus:run.calculation_status,supportStatus:completeness,requiredForms,generatedAt:new Date().toISOString(),...serviceManifest};
    await client.query(`INSERT INTO generated_artifacts(id,tax_year_id,calculation_run_id,artifact_type,artifact_key,template_version,artifact_status,completeness,storage_id,content_hash,manifest,artifact_bytes,mime_type,file_name,created_by_id,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,'succeeded',$7,$8,$9,$10::jsonb,$11,$12,$13,$14,$15)`,[artifactId,scope.taxYearId,run.id,artifactType,`${artifactType}:${scope.revision}`,definition.templateVersion,completeness,`database:${artifactId}`,contentHash,JSON.stringify(manifest),Buffer.from(bytes),definition.mimeType,fileName,context.userId,idempotencyKey]);
    await appendAuditEvent(client,context,scope.taxYearId,"artifact.generated","generated_artifact",artifactId,{revision:scope.revision,artifactType,calculationRunId:run.id,contentHash,completeness});
    return{id:artifactId,status:"succeeded",contentHash,replayed:false};
  });
}

export async function getArtifactState(context:AuthorizationContext,clientId:string,year:number){const client=await databasePool().connect();try{const scope=await authorizedTaxYear(client,context,clientId,year,"output.download",false);const result=await client.query<{id:string;artifact_type:ArtifactType;artifact_status:string;completeness:string;file_name:string|null;mime_type:string|null;content_hash:string|null;manifest:Record<string,unknown>;stale_at:Date|null;created_at:Date;calculation_run_id:string|null}>("SELECT id,artifact_type,artifact_status,completeness,file_name,mime_type,content_hash,manifest,stale_at,created_at,calculation_run_id FROM generated_artifacts WHERE tax_year_id=$1 ORDER BY created_at DESC,id DESC",[scope.taxYearId]);return{revision:scope.revision,canExportComplete:authorize(context,"identifier.reveal",{firmId:context.firmId,clientId}),artifacts:result.rows.map(row=>({id:row.id,type:row.artifact_type,status:row.artifact_status,completeness:row.completeness,fileName:row.file_name,mimeType:row.mime_type,contentHash:row.content_hash,manifest:row.manifest,stale:row.stale_at!==null,staleAt:row.stale_at?.toISOString()??null,createdAt:row.created_at.toISOString(),calculationRunId:row.calculation_run_id}))};}finally{client.release();}}

export async function downloadPersistedArtifact(context:AuthorizationContext,clientId:string,year:number,artifactId:string){const client=await databasePool().connect();try{const scope=await authorizedTaxYear(client,context,clientId,year,"output.download",false);const result=await client.query<{artifact_type:ArtifactType;artifact_status:string;artifact_bytes:Buffer|null;mime_type:string|null;file_name:string|null;content_hash:string|null}>("SELECT artifact_type,artifact_status,artifact_bytes,mime_type,file_name,content_hash FROM generated_artifacts WHERE id=$1 AND tax_year_id=$2",[artifactId,scope.taxYearId]);const row=result.rows[0];if(!row)throw new WorkflowError("not_found","Artifact was not found.");if(row.artifact_type==="complete_json"&&!authorize(context,"identifier.reveal",{firmId:context.firmId,clientId}))throw new WorkflowError("forbidden","Complete canonical export requires sensitive-identifier permission.");if(row.artifact_status!=="succeeded"||!row.artifact_bytes||!row.mime_type||!row.file_name)throw new WorkflowError("conflict","Artifact content is not available.");if(createHash("sha256").update(row.artifact_bytes).digest("hex")!==row.content_hash)throw new WorkflowError("conflict","Artifact integrity verification failed.");return{bytes:row.artifact_bytes,mimeType:row.mime_type,fileName:row.file_name,contentHash:row.content_hash};}finally{client.release();}}

async function assembleCanonicalData(client:pg.PoolClient,taxYearId:string,clientId:string,year:number,revision:number,firmId:string):Promise<CanonicalTaxReturnData>{const[people,dependents,answers,documents,forms,activities,mappings]=await Promise.all([
client.query<{role:string;legal_name:string;date_of_birth:string|null;address:Record<string,unknown>;facts:Record<string,unknown>}>("SELECT role,legal_name,date_of_birth::text,address,facts FROM people WHERE tax_year_id=$1",[taxYearId]),client.query<{id:string;legal_name:string;facts:Record<string,unknown>}>("SELECT id,legal_name,facts FROM dependents WHERE tax_year_id=$1",[taxYearId]),client.query<{id:string;question_id:string;answer:"yes"|"no"|"unknown";respondent_id:string;evidence:string|null;answered_at:Date;answer_revision:number}>("SELECT DISTINCT ON(question_id) id,question_id,answer,respondent_id,evidence,answered_at,answer_revision FROM intake_answers WHERE tax_year_id=$1 ORDER BY question_id,answer_revision DESC",[taxYearId]),client.query<any>("SELECT id,file_name,document_type,storage_id,mime_type,byte_length,page_count,checksum,duplicate_fingerprint,disposition,supersedes_document_id,scan_state FROM source_documents WHERE tax_year_id=$1 ORDER BY uploaded_at,id",[taxYearId]),client.query<any>("SELECT id,external_source_id,source_document_id,form_type,form_year,owner_role,owner_person_id,normalized_data,raw_fields,unmapped_fields,corrected,void,version FROM source_form_records WHERE tax_year_id=$1 AND effective AND NOT void ORDER BY created_at,id",[taxYearId]),client.query<any>("SELECT id,activity_type,name,owner_role,implementation_status,active FROM activities WHERE tax_year_id=$1 ORDER BY created_at,id",[taxYearId]),client.query<any>("SELECT id,source_record_id,source_field,source_amount::text,target_type,target_activity_id,allocation_method,allocated_amount::text,percentage::text,reason,mapping_status,version FROM source_mappings WHERE tax_year_id=$1 AND effective ORDER BY created_at,id",[taxYearId])]);
const person=(role:string)=>people.rows.find(row=>row.role===role);const toPerson=(row:typeof people.rows[number]|undefined)=>row?{legalName:row.legal_name,dateOfBirth:row.date_of_birth,address:row.address,facts:row.facts}:null;
return{schemaVersion:"1.0.0",taxYear:year,returnType:"1040",firmId,clientId,taxYearId,revision,taxpayer:toPerson(person("taxpayer"))??{},spouse:toPerson(person("spouse")),dependents:dependents.rows,intakeAnswers:answers.rows.map(row=>({id:row.id,questionId:row.question_id,answer:row.answer,respondentId:row.respondent_id,evidence:row.evidence,answeredAt:row.answered_at.toISOString(),revision:row.answer_revision})),sourceDocuments:documents.rows.map((row:any)=>({id:row.id,fileName:row.file_name,documentType:row.document_type,taxYear:year,issuer:null,recipientRole:"unknown",storageId:row.storage_id,mimeType:row.mime_type,checksum:row.checksum,byteLength:row.byte_length==null?null:Number(row.byte_length),pageCount:row.page_count,duplicateFingerprint:row.duplicate_fingerprint,disposition:row.disposition,supersedesDocumentId:row.supersedes_document_id,scanState:row.scan_state})),sourceForms:forms.rows.map((row:any)=>({id:row.id,externalSourceId:row.external_source_id,sourceDocumentId:row.source_document_id,formType:row.form_type,formYear:row.form_year,owner:row.owner_role,ownerPersonId:row.owner_person_id,corrected:row.corrected,void:row.void,version:row.version,rawFields:row.raw_fields,unmappedSourceFields:row.unmapped_fields,...row.normalized_data})),activities:activities.rows.map((row:any)=>({id:row.id,type:row.activity_type,name:row.name,owner:row.owner_role,implementationStatus:row.implementation_status,active:row.active})),mappings:mappings.rows.map((row:any)=>({id:row.id,sourceRecordId:row.source_record_id,sourceField:row.source_field,sourceAmount:asDecimalString(row.source_amount),targetType:row.target_type,targetActivityId:row.target_activity_id,allocationMethod:row.allocation_method,allocatedAmount:asDecimalString(row.allocated_amount),percentage:row.percentage==null?null:asDecimalString(row.percentage),reason:row.reason,status:row.mapping_status,version:row.version})),metadata:{exportRevision:revision,generatedBy:"Nexus Tax"}} as CanonicalTaxReturnData;}
async function readDiagnostics(client:pg.PoolClient,taxYearId:string):Promise<Diagnostic[]>{const result=await client.query<any>("SELECT code,severity,category,record_id,field_path,message,resolution_action FROM validation_issues WHERE tax_year_id=$1 AND resolved_at IS NULL ORDER BY created_at",[taxYearId]);return result.rows.map((row:any)=>({code:row.code,severity:row.severity,category:normalizeCategory(row.category),recordId:row.record_id,fieldPath:row.field_path,message:row.message,resolutionAction:row.resolution_action}));}
function normalizeCategory(category:string):Diagnostic["category"]{return({intake:"completeness",calculation_engine:"tax_logic",calculation_support:"calculation_support",mapping:"mapping",source_consistency:"source_consistency",structural:"structural",tax_logic:"tax_logic"} as Record<string,Diagnostic["category"]>)[category]??"structural";}
function requiredFormsForRun(result:Record<string,any>){const forms=["Form 1040"];if(result.forms?.scheduleB?.required)forms.push("Schedule B");if(result.forms?.scheduleC?.length)forms.push("Schedule C");if(result.forms?.scheduleSE?.length)forms.push("Schedule SE","Schedule 1","Schedule 2");if(result.forms?.form8995&&Number(result.forms.form8995.deduction)>0)forms.push("Form 8995");return forms;}
async function authorizedTaxYear(client:pg.PoolClient,context:AuthorizationContext,clientId:string,year:number,action:"output.generate"|"output.download",lock:boolean){const result=await client.query<{id:string;revision:number;firm_id:string}>(`SELECT ty.id,ty.revision,c.firm_id FROM tax_years ty JOIN clients c ON c.id=ty.client_id WHERE c.id=$1 AND ty.tax_year=$2 AND c.firm_id=$3 AND c.archived_at IS NULL ${lock?"FOR UPDATE OF ty":""}`,[clientId,year,context.firmId]);const row=result.rows[0];if(!row)throw new WorkflowError("not_found","Tax year was not found.");if(!authorize(context,action,{firmId:row.firm_id,clientId}))throw new WorkflowError("forbidden","Output access is not permitted.");return{taxYearId:row.id,revision:row.revision};}
function assertRevision(current:number,expected:number){if(current!==expected)throw new WorkflowError("conflict",`Tax year changed from revision ${expected} to ${current}; reload before generating outputs.`);}
async function appendAuditEvent(client:pg.PoolClient,context:AuthorizationContext,taxYearId:string,eventType:string,recordType:string,recordId:string,metadata:Record<string,unknown>){await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[context.firmId]);const previous=await client.query<{event_hash:string}>("SELECT event_hash FROM audit_events WHERE firm_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1",[context.firmId]);const previousHash=previous.rows[0]?.event_hash??null;const payload=JSON.stringify({firmId:context.firmId,taxYearId,actorId:context.userId,eventType,recordType,recordId,metadata,previousHash});const eventHash=createHash("sha256").update(payload).digest("hex");await client.query("INSERT INTO audit_events(firm_id,tax_year_id,actor_id,event_type,record_type,record_id,metadata,previous_hash,event_hash) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9)",[context.firmId,taxYearId,context.userId,eventType,recordType,recordId,JSON.stringify(metadata),previousHash,eventHash]);}
async function inTransaction<T>(work:(client:pg.PoolClient)=>Promise<T>){const client=await databasePool().connect();try{await client.query("BEGIN");const result=await work(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
