import "server-only";
import { createHash } from "node:crypto";
import type pg from "pg";
import { authorize, type AuthorizationContext } from "@/services/authorization";
import { acceptSourceFile, SourceFileError } from "@/services/source-file-service";
import { WorkflowError } from "./client-workflow-service";
import { databasePool } from "./database";
import { ConfiguredFileScanner, DatabaseEncryptedObjectStore } from "./encrypted-source-store";

export const sourceDocumentTypes=["W2","1099-NEC","1099-MISC","1099-INT","1099-DIV","W2C","OTHER"] as const;
export type SourceDocumentType=typeof sourceDocumentTypes[number];

export async function uploadSourceDocument(context:AuthorizationContext,clientId:string,year:number,expectedRevision:number,input:{fileName:string;mimeType:string;bytes:Uint8Array;documentType:SourceDocumentType}){
  await assertUploadScope(context,clientId,year,expectedRevision);
  let accepted;try{accepted=await acceptSourceFile({fileName:input.fileName,declaredMimeType:input.mimeType,bytes:input.bytes},new ConfiguredFileScanner(),new DatabaseEncryptedObjectStore());}catch(error){if(error instanceof SourceFileError)throw new WorkflowError("invalid",error.message);throw error;}
  return inTransaction(async client=>{const scope=await authorizedTaxYear(client,context,clientId,year,"source.modify",true);assertRevision(scope.revision,expectedRevision);const duplicate=await client.query<{id:string}>("SELECT id FROM source_documents WHERE tax_year_id=$1 AND checksum=$2 AND scan_state='clean' ORDER BY uploaded_at LIMIT 1",[scope.taxYearId,accepted.checksum]);
    await client.query(`INSERT INTO source_documents(id,tax_year_id,file_name,document_type,storage_id,mime_type,byte_length,checksum,duplicate_fingerprint,scan_state,storage_version,uploaded_by,scanner_version,scan_completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,'clean',$9,$10,$11,now())`,[accepted.id,scope.taxYearId,accepted.sanitizedName,input.documentType,accepted.storageId,accepted.mimeType,accepted.byteLength,accepted.checksum,Number(accepted.storageVersion),context.userId,accepted.scannerVersion]);const revision=scope.revision+1;await invalidateTaxYear(client,scope.taxYearId,revision);if(duplicate.rows[0])await client.query("INSERT INTO validation_issues(tax_year_id,code,severity,category,record_id,message,resolution_action,creation_revision) VALUES($1,'POSSIBLE_DUPLICATE_SOURCE','warning','source_consistency',$2,$3,'Compare both originals and explicitly classify the duplicate or correction.',$4)",[scope.taxYearId,accepted.id,`${accepted.sanitizedName} has the same content hash as another source document.`,revision]);await appendAuditEvent(client,context,scope.taxYearId,"source_document.uploaded","source_document",accepted.id,{revision,documentType:input.documentType,mimeType:accepted.mimeType,byteLength:accepted.byteLength,checksum:accepted.checksum,scannerVersion:accepted.scannerVersion,possibleDuplicateOf:duplicate.rows[0]?.id??null});return{id:accepted.id,revision,possibleDuplicateOf:duplicate.rows[0]?.id??null};});
}

export async function getSourceDocumentState(context:AuthorizationContext,clientId:string,year:number){const client=await databasePool().connect();try{const scope=await authorizedTaxYear(client,context,clientId,year,"source.download",false);const result=await client.query<{id:string;file_name:string;document_type:string;mime_type:string|null;byte_length:string|null;checksum:string|null;disposition:string;scan_state:string;storage_version:number;scanner_version:string|null;uploaded_at:Date;uploaded_by_name:string|null;duplicate_count:string}>(`SELECT sd.id,sd.file_name,sd.document_type,sd.mime_type,sd.byte_length::text,sd.checksum,sd.disposition,sd.scan_state,sd.storage_version,sd.scanner_version,sd.uploaded_at,u.display_name AS uploaded_by_name,(SELECT count(*)::text FROM source_documents sibling WHERE sibling.tax_year_id=sd.tax_year_id AND sibling.checksum=sd.checksum AND sibling.id<>sd.id) duplicate_count FROM source_documents sd LEFT JOIN users u ON u.id=sd.uploaded_by WHERE sd.tax_year_id=$1 ORDER BY sd.uploaded_at DESC,sd.id DESC`,[scope.taxYearId]);return{revision:scope.revision,limits:{maximumBytes:25*1024*1024,allowedTypes:["application/pdf","image/png","image/jpeg"]},documents:result.rows.map(row=>({id:row.id,fileName:row.file_name,documentType:row.document_type,mimeType:row.mime_type,byteLength:row.byte_length===null?null:Number(row.byte_length),checksum:row.checksum,disposition:row.disposition,scanState:row.scan_state,storageVersion:row.storage_version,scannerVersion:row.scanner_version,uploadedAt:row.uploaded_at.toISOString(),uploadedBy:row.uploaded_by_name,possibleDuplicate:Number(row.duplicate_count)>0}))};}finally{client.release();}}

export async function downloadSourceDocument(context:AuthorizationContext,clientId:string,year:number,documentId:string){const client=await databasePool().connect();try{await client.query("BEGIN");const scope=await authorizedTaxYear(client,context,clientId,year,"source.download",false);const result=await client.query<{file_name:string;mime_type:string|null;checksum:string|null;storage_id:string|null;scan_state:string}>("SELECT file_name,mime_type,checksum,storage_id,scan_state FROM source_documents WHERE id=$1 AND tax_year_id=$2",[documentId,scope.taxYearId]);const row=result.rows[0];if(!row)throw new WorkflowError("not_found","Source document was not found.");if(row.scan_state!=="clean"||!row.storage_id||!row.mime_type||!row.checksum)throw new WorkflowError("conflict","Source document is not approved for viewing.");let bytes;try{bytes=await new DatabaseEncryptedObjectStore().readPromoted(row.storage_id);}catch(error){if(error instanceof SourceFileError)throw new WorkflowError("conflict",error.message);throw error;}if(createHash("sha256").update(bytes).digest("hex")!==row.checksum)throw new WorkflowError("conflict","Source document hash verification failed.");await appendAuditEvent(client,context,scope.taxYearId,"source_document.viewed","source_document",documentId,{delivery:"authenticated_proxy"});await client.query("COMMIT");return{bytes,fileName:row.file_name,mimeType:row.mime_type,checksum:row.checksum};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

async function assertUploadScope(context:AuthorizationContext,clientId:string,year:number,expectedRevision:number){const client=await databasePool().connect();try{const scope=await authorizedTaxYear(client,context,clientId,year,"source.modify",false);assertRevision(scope.revision,expectedRevision);}finally{client.release();}}
async function authorizedTaxYear(client:pg.PoolClient,context:AuthorizationContext,clientId:string,year:number,action:"source.modify"|"source.download",lock:boolean){const result=await client.query<{id:string;revision:number;firm_id:string}>(`SELECT ty.id,ty.revision,c.firm_id FROM tax_years ty JOIN clients c ON c.id=ty.client_id WHERE c.id=$1 AND ty.tax_year=$2 AND c.firm_id=$3 AND c.archived_at IS NULL ${lock?"FOR UPDATE OF ty":""}`,[clientId,year,context.firmId]);const row=result.rows[0];if(!row)throw new WorkflowError("not_found","Tax year was not found.");if(!authorize(context,action,{firmId:row.firm_id,clientId}))throw new WorkflowError("forbidden","Source-document access is not permitted.");return{taxYearId:row.id,revision:row.revision};}
function assertRevision(current:number,expected:number){if(current!==expected)throw new WorkflowError("conflict",`Tax year changed from revision ${expected} to ${current}; reload before uploading.`);}
async function invalidateTaxYear(client:pg.PoolClient,taxYearId:string,revision:number){await client.query("UPDATE tax_years SET revision=$2,validation_status='not_run',calculation_status='stale',preparation_status=CASE WHEN preparation_status IN ('ready_for_review','reviewed_draft') THEN 'changes_requested' ELSE preparation_status END WHERE id=$1",[taxYearId,revision]);}
async function appendAuditEvent(client:pg.PoolClient,context:AuthorizationContext,taxYearId:string,eventType:string,recordType:string,recordId:string,metadata:Record<string,unknown>){await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[context.firmId]);const previous=await client.query<{event_hash:string}>("SELECT event_hash FROM audit_events WHERE firm_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1",[context.firmId]);const previousHash=previous.rows[0]?.event_hash??null;const payload=JSON.stringify({firmId:context.firmId,taxYearId,actorId:context.userId,eventType,recordType,recordId,metadata,previousHash});const eventHash=createHash("sha256").update(payload).digest("hex");await client.query("INSERT INTO audit_events(firm_id,tax_year_id,actor_id,event_type,record_type,record_id,metadata,previous_hash,event_hash) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9)",[context.firmId,taxYearId,context.userId,eventType,recordType,recordId,JSON.stringify(metadata),previousHash,eventHash]);}
async function inTransaction<T>(work:(client:pg.PoolClient)=>Promise<T>){const client=await databasePool().connect();try{await client.query("BEGIN");const result=await work(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
