import type { ClientSummary, Diagnostic, W2Record } from "./types";

export const clients: ClientSummary[] = [
  {
    id: "sample",
    code: "000123",
    taxpayer: "John Sample",
    spouse: "Jane Sample",
    maskedTin: "***-**-6789",
    returnType: "1040",
    taxYear: 2025,
    status: "In Preparation",
    preparer: "Maya Chen",
    reviewer: "David Ross",
    openPoints: 4,
    blockers: 2,
    updatedAt: "Today, 9:42 AM",
  },
  {
    id: "supported",
    code: "000124",
    taxpayer: "Alex Rivera",
    maskedTin: "***-**-1194",
    returnType: "1040",
    taxYear: 2025,
    status: "Ready for Review",
    preparer: "Maya Chen",
    reviewer: "David Ross",
    openPoints: 0,
    blockers: 0,
    updatedAt: "Yesterday, 4:18 PM",
  },
  {
    id: "changes",
    code: "000125",
    taxpayer: "Priya Shah",
    spouse: "Amir Shah",
    maskedTin: "***-**-8831",
    returnType: "1040",
    taxYear: 2025,
    status: "Changes Requested",
    preparer: "Noah Williams",
    reviewer: "Elena Park",
    openPoints: 2,
    blockers: 1,
    updatedAt: "Oct 5, 2:07 PM",
  },
  {
    id: "documents",
    code: "000126",
    taxpayer: "Morgan Lee",
    maskedTin: "***-**-0247",
    returnType: "1040",
    taxYear: 2025,
    status: "Documents Pending",
    preparer: "Noah Williams",
    reviewer: "Unassigned",
    openPoints: 1,
    blockers: 3,
    updatedAt: "Oct 4, 11:31 AM",
  },
];

export const w2Records: W2Record[] = [
  {
    id: "w2-001",
    employer: "Northstar Systems, Inc.",
    owner: "TP",
    ein: "**-***4821",
    wages: "86000.00",
    withholding: "7200.00",
    ssWages: "86000.00",
    ssWithholding: "5332.00",
    medicareWages: "86000.00",
    medicareWithholding: "1247.00",
    status: "verified",
    source: "2025_W2_Northstar.pdf",
  },
  {
    id: "w2-002",
    employer: "Harbor & Pine Studio",
    owner: "SP",
    ein: "**-***1092",
    wages: "40000.00",
    withholding: "3650.00",
    ssWages: "40000.00",
    ssWithholding: "2480.00",
    medicareWages: "40000.00",
    medicareWithholding: "580.00",
    status: "warning",
    source: "2025_W2_HarborPine.pdf",
  },
];

export const diagnostics: Diagnostic[] = [
  {
    code: "INTAKE_INVESTMENT_SALES_UNKNOWN",
    severity: "blocking",
    title: "Investment sales answer is unknown",
    detail: "The income inventory cannot rule out Form 8949 and Schedule D.",
    action: "Complete intake",
  },
  {
    code: "MISC_RENT_MAPPING_ONLY",
    severity: "blocking",
    title: "Rental income maps to unsupported Schedule E",
    detail: "$12,000.00 is preserved and mapped, but Phase 1 cannot calculate this treatment.",
    action: "Review treatment",
  },
  {
    code: "W2_BOX14_UNCLASSIFIED",
    severity: "warning",
    title: "W-2 Box 14 item needs classification",
    detail: "UT SDI was preserved from Harbor & Pine Studio and has no selected disposition.",
    action: "Open W-2",
  },
];

export const money = (value: string | number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(Number(value));
