"use client";
import { AlertCircle, ArrowLeft, CheckCircle2, RotateCcw, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

interface OverrideState { revision:number; canReview:boolean; canRevert:boolean; currentCalculation:{id:string;inputRevision:number;status:string;current:boolean;createdAt:string}|null; registeredPoints:Array<{id:string;label:string;unit:string;downstreamPaths:string[];engineValue:string|null;available:boolean}>; overrides:Array<{id:string;overridePoint:string;label:string;engineValue:string;overrideValue:string;unit:string;reason:string;evidence:string;actorName:string;approvedByName:string|null;status:string;active:boolean;creationRevision:number;version:number;downstreamPaths:string[];reviewNote:string|null;createdAt:string}> }
export function PersistedOverrides({clientId,year,clientName,initial}:{clientId:string;year:number;clientName:string;initial:OverrideState}){
  const router=useRouter(); const base=`/api/clients/${clientId}/years/${year}/overrides`;
  const [form,setForm]=useState({overridePoint:initial.registeredPoints.find(({available})=>available)?.id??"",overrideValue:"",reason:"",evidence:""});
  const [notes,setNotes]=useState<Record<string,string>>({}); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  async function request(url:string,method:string,body:unknown){setSaving(true);setError(null);const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setSaving(false);if(!response.ok){setError(result.message??result.error??"Request failed.");return false;}router.refresh();return true;}
  const selected=initial.registeredPoints.find(({id})=>id===form.overridePoint);
  return <div className="return-page"><div className="return-page-top"><Link href={`/clients/${clientId}/years/${year}/review`}><ArrowLeft size={14}/> {clientName} · review</Link><span>Revision {initial.revision}</span><b>{initial.overrides.filter(({status})=>status==="pending_review").length} pending</b></div><header><div><p>REVIEW · GOVERNED ADJUSTMENTS</p><h1>Manual calculation overrides</h1><span>Only registered trace points can be requested. Approval forces a new revision and recalculation.</span></div></header>
    {error?<p className="form-error" role="alert">{error}</p>:null}
    <div className="override-layout"><section className="panel"><div className="panel-heading"><div><h2>Request override</h2><p>{initial.currentCalculation?.current?`Current ${initial.currentCalculation.status} run · revision ${initial.currentCalculation.inputRevision}`:"No current persisted calculation is available."}</p></div><button className="button primary" disabled={saving||!selected?.available||!form.overrideValue||!form.reason.trim()||!form.evidence.trim()} onClick={()=>request(base,"POST",{expectedRevision:initial.revision,...form})}>Submit for review</button></div><div className="override-form"><label><span>Registered trace point</span><select value={form.overridePoint} onChange={event=>setForm({...form,overridePoint:event.target.value})}><option value="">Select available point</option>{initial.registeredPoints.map(point=><option key={point.id} value={point.id} disabled={!point.available}>{point.label}{point.engineValue?` · engine $${point.engineValue}`:" · unavailable"}</option>)}</select></label><label><span>Override value (USD)</span><input inputMode="decimal" value={form.overrideValue} onChange={event=>setForm({...form,overrideValue:event.target.value})}/></label><label><span>Professional reason</span><textarea value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label><label><span>Evidence reference</span><textarea value={form.evidence} onChange={event=>setForm({...form,evidence:event.target.value})}/></label>{selected?<div className="override-impact"><AlertCircle size={15}/><div><b>Downstream recalculation required</b><span>{selected.downstreamPaths.join(" · ")}</span></div></div>:null}</div></section><aside className="panel compact-panel"><h2>Controls</h2><p>Requester and approver must be different users. An approved override cannot clear source, mapping, intake or unsupported-treatment blockers. Revert creates another revision; history is retained.</p></aside></div>
    <section className="panel override-history"><div className="panel-heading"><div><h2>Override history</h2><p>Engine and override values remain visible for every decision.</p></div></div>{initial.overrides.map(record=><article key={record.id}><span className={`override-status ${record.status}`}>{record.active?<CheckCircle2 size={14}/>:record.status==="reverted"?<RotateCcw size={14}/>:<ShieldCheck size={14}/>} {record.status.replaceAll("_"," ")}</span><div><b>{record.label}</b><p>Engine ${record.engineValue} → requested ${record.overrideValue}</p><small>{record.actorName} · revision {record.creationRevision} · {record.reason}</small><em>Downstream: {record.downstreamPaths.join(" · ")}</em></div><div className="override-actions"><input placeholder="Independent review / revert evidence" value={notes[record.id]??""} onChange={event=>setNotes({...notes,[record.id]:event.target.value})}/>{record.status==="pending_review"&&initial.canReview?<><button className="button secondary" disabled={saving||!(notes[record.id]??"").trim()} onClick={()=>request(`${base}/${record.id}`,"PATCH",{action:"review",expectedRevision:initial.revision,expectedVersion:record.version,decision:"rejected",reviewNote:notes[record.id]})}>Reject</button><button className="button primary" disabled={saving||!(notes[record.id]??"").trim()} onClick={()=>request(`${base}/${record.id}`,"PATCH",{action:"review",expectedRevision:initial.revision,expectedVersion:record.version,decision:"approved",reviewNote:notes[record.id]})}>Approve</button></>:null}{record.active&&initial.canRevert?<button className="button secondary" disabled={saving||!(notes[record.id]??"").trim()} onClick={()=>request(`${base}/${record.id}`,"PATCH",{action:"revert",expectedRevision:initial.revision,expectedVersion:record.version,reason:notes[record.id]})}>Revert</button>:null}</div></article>)}{!initial.overrides.length?<p className="empty-panel">No override requests have been recorded.</p>:null}</section>
  </div>;
}
