"use client";
import { AlertTriangle, ArrowLeft, CheckCircle2, Eye, FileImage, FileText, LockKeyhole, Upload } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";

interface SourceRecord{id:string;fileName:string;documentType:string;mimeType:string|null;byteLength:number|null;checksum:string|null;disposition:string;scanState:string;storageVersion:number;scannerVersion:string|null;uploadedAt:string;uploadedBy:string|null;possibleDuplicate:boolean}
interface SourceState{revision:number;limits:{maximumBytes:number;allowedTypes:string[]};documents:SourceRecord[]}
const types=["W2","1099-NEC","1099-MISC","1099-INT","1099-DIV","W2C","OTHER"];
export function PersistedSources({clientId,year,clientName,initial}:{clientId:string;year:number;clientName:string;initial:SourceState}){const router=useRouter();const fileRef=useRef<HTMLInputElement>(null);const[type,setType]=useState("W2");const[uploading,setUploading]=useState(false);const[error,setError]=useState<string|null>(null);async function upload(){const file=fileRef.current?.files?.[0];if(!file){setError("Choose a PDF, PNG, or JPEG source file.");return;}const body=new FormData();body.set("expectedRevision",String(initial.revision));body.set("documentType",type);body.set("file",file);setUploading(true);setError(null);const response=await fetch(`/api/clients/${clientId}/years/${year}/sources`,{method:"POST",body});const result=await response.json();setUploading(false);if(!response.ok){setError(result.message??result.error??"Upload failed.");return;}if(fileRef.current)fileRef.current.value="";router.refresh();}
return <div className="return-page source-page"><div className="return-page-top"><Link href={`/clients/${clientId}/years/${year}`}><ArrowLeft size={14}/> {clientName} · {year}</Link><span>Revision {initial.revision}</span><b>{initial.documents.length} source files</b></div><header><div><p>SOURCE DOCUMENTS · ENCRYPTED STORAGE</p><h1>Secure source intake</h1><span>Files are signature-checked, quarantined, scanned, encrypted with authenticated encryption, and served only through an authorized no-store proxy.</span></div></header><section className="panel source-upload"><div><LockKeyhole size={19}/><span><b>25 MiB maximum</b><small>PDF, PNG or JPEG · active PDF actions blocked · production scanner required outside development</small></span></div><select aria-label="Document type" value={type} onChange={event=>setType(event.target.value)}>{types.map(value=><option key={value}>{value}</option>)}</select><input ref={fileRef} type="file" accept="application/pdf,image/png,image/jpeg"/><button className="button primary" disabled={uploading} onClick={upload}><Upload size={13}/>{uploading?"Scanning…":"Upload and scan"}</button></section>{error?<p className="form-error" role="alert">{error}</p>:null}<section className="panel source-history"><div className="panel-heading"><div><h2>Stored originals</h2><p>Checksums identify possible duplicates; they never silently decide which document is authoritative.</p></div></div>{initial.documents.length?<div className="source-table"><div className="source-row source-head"><span>Document</span><span>Security</span><span>Uploaded</span><span>Integrity</span><span>View</span></div>{initial.documents.map(document=><div className="source-row" key={document.id}><span className="source-name">{document.mimeType?.startsWith("image/")?<FileImage size={16}/>:<FileText size={16}/>}<span><b>{document.fileName}</b><small>{document.documentType} · {formatBytes(document.byteLength)}</small></span></span><span className={document.scanState==="clean"?"artifact-current":"artifact-stale"}>{document.scanState==="clean"?<CheckCircle2 size={13}/>:<AlertTriangle size={13}/>} {document.scanState}<small>{document.scannerVersion}</small></span><span>{new Date(document.uploadedAt).toLocaleString()}<small>{document.uploadedBy??"Unknown uploader"}</small></span><span><code>{document.checksum?.slice(0,16)??"—"}</code>{document.possibleDuplicate?<small className="duplicate-label">Possible duplicate</small>:<small>SHA-256 verified</small>}</span><span><a className="button secondary" target="_blank" rel="noreferrer" href={`/api/clients/${clientId}/years/${year}/sources/${document.id}/download`}><Eye size={13}/> View</a></span></div>)}</div>:<p className="empty-panel">No source originals are attached to this tax year.</p>}</section></div>}
function formatBytes(value:number|null){if(value===null)return"size unavailable";if(value<1024)return`${value} B`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KiB`;return`${(value/1024/1024).toFixed(1)} MiB`;}
