"use client";
import { AlertCircle, ArrowLeft, Calculator, CheckCircle2, ChevronRight, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

interface EngineDiagnostic {code:string;severity:string;message:string;path:string|null}
interface CalculationResult {status:string;rulePackageId:string;rulePackageVersion:string;rulePackageApproval:string;diagnostics:EngineDiagnostic[];forms:null|{form1040:Record<string,string>;schedule1:Record<string,string>;schedule2:Record<string,string>;scheduleB:Record<string,string|boolean>;form8995:Record<string,string>;scheduleC:Array<Record<string,string>>;scheduleSE:Array<Record<string,string>>};trace:Array<{nodeId:string;formLine:string;ruleId:string;operands:Record<string,string>;result:string;rounding:string}>;dependencyManifest:Array<{nodeId:string;dependsOn:string[];status:string}>}
interface CalculationState {revision:number;calculationStatus:string;issues:Array<{code:string;severity:string;message:string;fieldPath:string|null}>;latestRun:null|{id:string;inputRevision:number;current:boolean;inputHash:string;engineVersion:string;ruleVersion:string;formRegistryVersion:string;status:string;result:CalculationResult;resultHash:string|null;createdAt:string;completedAt:string|null}}
const lineLabels:Record<string,string>={wages:"Wages",taxExemptInterest:"Tax-exempt interest",taxableInterest:"Taxable interest",qualifiedDividends:"Qualified dividends",ordinaryDividends:"Ordinary dividends",totalIncome:"Total income",adjustedGrossIncome:"Adjusted gross income",standardDeduction:"Standard deduction",qbiDeduction:"QBI deduction",taxableIncome:"Taxable income",incomeTax:"Income tax",selfEmploymentTax:"Self-employment tax",totalTax:"Total tax",federalWithholding:"Federal withholding",refund:"Refund",amountOwed:"Amount owed"};
export function PersistedCalculation({clientId,year,clientName,initial}:{clientId:string;year:number;clientName:string;initial:CalculationState}){const router=useRouter();const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const run=initial.latestRun;const result=run?.result;async function calculate(){setSaving(true);setError(null);const response=await fetch(`/api/clients/${clientId}/years/${year}/calculation`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedRevision:initial.revision})});const body=await response.json();setSaving(false);if(!response.ok){setError(body.message??body.error??"Calculation failed.");return;}router.refresh();}
return <div className="return-page"><div className="return-page-top"><Link href={`/clients/${clientId}/years/${year}`}><ArrowLeft size={14}/> {clientName} · {year}</Link><span>Revision {initial.revision}</span><b>{initial.issues.filter(({severity})=>severity==="blocking"||severity==="error").length} blockers</b></div><header><div><p>CALCULATION · IMMUTABLE SNAPSHOTS</p><h1>Federal tax summary</h1><span>Every run is hashed and pinned to the input, engine, rule and form-registry versions.</span></div><button className="button primary" disabled={saving} onClick={calculate}><Calculator size={14}/>{saving?"Calculating…":run?.current?"Recalculate current revision":"Calculate current revision"}</button></header>{error?<p className="form-error" role="alert">{error}</p>:null}
{run?<div className={`calculation-banner ${run.current?"":"stale-run"}`}>{run.current?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}<div><strong>{run.status} calculation · {run.current?"current":"stale"}</strong><span>Run {run.id.slice(0,12)} · input revision {run.inputRevision} · result {run.resultHash?.slice(0,12)??"hash unavailable"}</span></div></div>:<div className="calculation-banner"><AlertCircle size={16}/><div><strong>No persisted calculation</strong><span>Run the deterministic engine to create the first immutable snapshot.</span></div></div>}
<div className="screen-grid-main"><section className="panel calculation-panel">{result?.forms?<div className="calc-section"><h2>Form 1040</h2>{Object.entries(result.forms.form1040).map(([key,value])=><div className={`calc-line ${["totalIncome","adjustedGrossIncome","taxableIncome","totalTax","refund","amountOwed"].includes(key)?"total":""}`} key={key}><span><strong>{lineLabels[key]??key}</strong><small>Current immutable engine result</small></span><b>{money(value)}</b><ChevronRight size={14}/></div>)}</div>:<div className="calc-section unavailable"><h2>Final totals unavailable</h2><p><ShieldAlert size={15}/> The engine intentionally withheld forms because required facts, mappings, treatment screens or supported dependencies remain blocked.</p></div>}{result?.trace?.length?<div className="calc-section"><h2>Calculation trace</h2>{result.trace.map(step=><details className="trace-step" key={step.nodeId}><summary><span>{step.formLine}<small>{step.ruleId} · {step.rounding.replaceAll("_"," ")}</small></span><b>{money(step.result)}</b></summary><pre>{JSON.stringify(step.operands,null,2)}</pre></details>)}</div>:null}</section><aside className="side-stack"><section className="panel compact-panel"><h2>Run manifest</h2>{run?<dl className="manifest"><div><dt>Input revision</dt><dd>{run.inputRevision}{run.current?" · current":" · stale"}</dd></div><div><dt>Engine</dt><dd>{run.engineVersion}</dd></div><div><dt>Rules</dt><dd>{run.ruleVersion}</dd></div><div><dt>Forms</dt><dd>{run.formRegistryVersion}</dd></div><div><dt>Input hash</dt><dd>{run.inputHash.slice(0,12)}</dd></div><div><dt>Result hash</dt><dd>{run.resultHash?.slice(0,12)??"—"}</dd></div></dl>:<p>No manifest yet.</p>}</section><section className="panel compact-panel"><h2>Diagnostics</h2><div className="calculation-diagnostics">{(result?.diagnostics??initial.issues.slice(0,12)).map((issue,index)=><div key={`${issue.code}-${index}`}><AlertCircle size={13}/><span><b>{issue.code}</b>{issue.message}</span></div>)}</div></section><section className="panel compact-panel"><h2>Release gate</h2><p>{result?.rulePackageApproval==="approved"?"The rule package is approved.":"The archived 2025 package remains research_unapproved. Calculations are reproducible but cannot be promoted to Reviewed Draft until independent tax review is recorded."}</p></section></aside></div></div>}
function money(value:string){return Number(value).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});}
