"use client";

import { AlertCircle, ArrowLeft, ArrowRight, Check, CheckCircle2, CircleHelp, FileJson, FileSpreadsheet, Link2, LockKeyhole, Plus, Upload, XCircle } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { phase1IntakeQuestions } from "@/domain/intake";
import { diagnostics } from "@/domain/demo-data";
import { SeverityIcon } from "./status";

export function ReturnPageFrame({ title, subtitle, children, action }: { title: string; subtitle: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <div className="return-page"><div className="return-page-top"><Link href="/clients/sample/years/2025"><ArrowLeft size={14} /> John &amp; Jane Sample · 2025</Link><span>In Preparation</span><b>2 blockers</b></div><header><div><p>CLIENT 000123 · TAX YEAR 2025</p><h1>{title}</h1><span>{subtitle}</span></div>{action}</header>{children}</div>;
}

export function IntakeScreen() {
  const [answers, setAnswers] = useState<Record<string, "yes" | "no" | "unknown">>(() => Object.fromEntries(phase1IntakeQuestions.map((q, i) => [q.id, i < 3 ? "no" : "unknown"])));
  const unknown = Object.values(answers).filter((answer) => answer === "unknown").length;
  const groups = useMemo(() => Map.groupBy(phase1IntakeQuestions, (question) => question.group), []);
  return <ReturnPageFrame title="Intake & completeness" subtitle="Every required answer is versioned. Unknown never means no." action={<button className="button primary" disabled={unknown > 0}><Check size={14} /> Attest documents complete</button>}>
    <div className="intake-summary"><div><strong>{phase1IntakeQuestions.length - unknown}</strong><span>Answered</span></div><div className="warn"><strong>{unknown}</strong><span>Unknown</span></div><div><strong>14 / 17</strong><span>Expected documents received</span></div><p><AlertCircle size={15} /> Completion remains blocked until all required answers and expected-document evidence are resolved.</p></div>
    <div className="screen-grid-main"><section className="panel"><div className="panel-heading"><div><h2>Required screening</h2><p>Phase 1 eligibility and dependency questions</p></div></div>{[...groups.entries()].map(([group, questions]) => <div className="question-group" key={group}><h3>{group.replace("_", " ")}</h3>{questions.map((question) => <div className="question-row" key={question.id}><div><strong>{question.prompt}</strong><span>{question.affirmativeTreatment}{question.supportedWhenYes ? " · Supported when confirmed" : " · May require unsupported treatment"}</span></div><fieldset aria-label={question.prompt}>{(["yes", "no", "unknown"] as const).map((answer) => <label key={answer} className={answers[question.id] === answer ? "selected" : ""}><input type="radio" name={question.id} checked={answers[question.id] === answer} onChange={() => setAnswers((current) => ({ ...current, [question.id]: answer }))} />{answer}</label>)}</fieldset></div>)}</div>)}</section>
      <aside className="side-stack"><section className="panel compact-panel"><h2>Expected documents</h2>{["W-2 · Northstar Systems", "W-2 · Harbor & Pine", "1099 consolidated statements", "Prior-year return", "Business receipts support"].map((item, index) => <div className="check-row" key={item}>{index < 3 ? <CheckCircle2 size={15} /> : <CircleHelp size={15} />}<span>{item}</span><b>{index < 3 ? "Received" : "Pending"}</b></div>)}</section><section className="panel compact-panel"><h2>Release effect</h2><p>Unknown and affirmative unsupported answers create blocking diagnostics. They cannot be waived by an administrator.</p></section></aside>
    </div>
  </ReturnPageFrame>;
}

export function MappingScreen() {
  const [first, setFirst] = useState("75000.00");
  const source = 100000;
  const allocated = Number(first) + 25000;
  const remaining = source - allocated;
  return <ReturnPageFrame title="Mapping center" subtitle="Allocate source amounts to return activities without losing tax character." action={<button className="button primary"><Plus size={14} /> Add activity</button>}>
    <div className="mapping-layout"><section className="panel mapping-sources"><div className="panel-heading"><div><h2>Source amounts</h2><p>2 unresolved fields</p></div></div>{[{ form: "1099-NEC", payer: "Acme Advisory LLC", box: "Box 1", amount: "$100,000.00", active: true }, { form: "1099-MISC", payer: "West Lake Property", box: "Box 1 rents", amount: "$12,000.00", active: false }].map((sourceItem) => <button className={`mapping-source ${sourceItem.active ? "active" : ""}`} key={sourceItem.payer}><span>{sourceItem.form}</span><strong>{sourceItem.payer}</strong><small>{sourceItem.box}</small><b>{sourceItem.amount}</b><em>{sourceItem.active ? "Partially mapped" : "Mapping only"}</em></button>)}</section>
      <section className="panel mapping-editor"><div className="panel-heading"><div><h2>Acme Advisory LLC · 1099-NEC</h2><p>Box 1 — Nonemployee compensation · Owner: Taxpayer</p></div></div><div className="mapping-source-total"><span>Effective source amount</span><strong>$100,000.00</strong></div><div className="allocation-table"><div className="allocation-head"><span>Destination activity</span><span>Method</span><span>Amount</span><span /></div><div className="allocation-row"><select aria-label="First destination"><option>John Consulting · Schedule C</option></select><select aria-label="First allocation method"><option>Amount</option></select><label><span>$</span><input value={first} onChange={(event) => setFirst(event.target.value)} /></label><button aria-label="Remove allocation"><XCircle size={15} /></button></div><div className="allocation-row"><select aria-label="Second destination"><option>Training Services · Schedule C</option></select><select aria-label="Second allocation method"><option>Amount</option></select><label><span>$</span><input defaultValue="25000.00" /></label><button aria-label="Remove allocation"><XCircle size={15} /></button></div><button className="add-allocation"><Plus size={13} /> Add allocation</button></div><div className="mapping-note"><label><span>Mapping note</span><textarea defaultValue="Split confirmed against client-provided receipts ledger." /></label></div></section>
      <aside className="panel reconciliation"><h2>Reconciliation</h2><dl><div><dt>Source amount</dt><dd>$100,000.00</dd></div><div><dt>Accepted allocations</dt><dd>${allocated.toLocaleString("en-US", { minimumFractionDigits: 2 })}</dd></div><div className={remaining === 0 ? "total good" : "total bad"}><dt>Unresolved remainder</dt><dd>${remaining.toLocaleString("en-US", { minimumFractionDigits: 2 })}</dd></div></dl><p className={remaining === 0 ? "reconcile-state good" : "reconcile-state bad"}>{remaining === 0 ? <CheckCircle2 size={15} /> : <AlertCircle size={15} />}{remaining === 0 ? "Fully mapped" : remaining < 0 ? "Over-allocated" : "Partially mapped"}</p><hr /><h3>Tax treatment</h3><p>Both targets are supported Schedule C activities. Withholding follows the source payment ledger and is counted once.</p></aside>
    </div>
  </ReturnPageFrame>;
}

export function ReviewScreen() {
  return <ReturnPageFrame title="Review & diagnostics" subtitle="Machine findings and human review points for revision 28." action={<button className="button primary"><Plus size={14} /> Add review point</button>}>
    <div className="review-metrics">{[["14", "Source documents"], ["18", "Source records"], ["2", "Blocking errors"], ["5", "Warnings"], ["2", "Unmapped amounts"], ["4", "Open points"]].map(([value, label], index) => <div className={index === 2 ? "danger" : ""} key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>Current findings</h2><p>Filters: Open · All owners · All categories</p></div><button className="button secondary">Export list</button></div><table className="review-table"><thead><tr><th>Severity</th><th>Code / issue</th><th>Source</th><th>Owner</th><th>Assignee</th><th>Status</th><th>Action</th></tr></thead><tbody>{diagnostics.map((issue, index) => <tr key={issue.code}><td><span className={`severity-cell ${issue.severity}`}><SeverityIcon severity={issue.severity} />{issue.severity}</span></td><td><strong>{issue.title}</strong><small>{issue.code}</small><p>{issue.detail}</p></td><td>{index === 0 ? "Intake" : index === 1 ? "1099-MISC #1" : "W-2 #2"}</td><td>{index === 1 ? "TP" : "Return"}</td><td>{index === 2 ? "Maya Chen" : "Unassigned"}</td><td><span className="open-state">Open</span></td><td><button className="text-action">{issue.action} <ArrowRight size={13} /></button></td></tr>)}</tbody></table></section>
    <div className="approval-bar"><LockKeyhole size={18} /><div><strong>Reviewed Draft is unavailable</strong><span>2 blocking diagnostics, incomplete intake, and a stale partial calculation must be resolved on the same return revision.</span></div><button disabled>Mark Reviewed Draft</button></div>
  </ReturnPageFrame>;
}

export function CalculationSummaryScreen() {
  const lines = [["Wages", "$126,000", "2 W-2 records"], ["Taxable interest", "$5,000", "3 1099-INT records"], ["Ordinary dividends", "$12,000", "2 1099-DIV records"], ["Schedule C receipts", "$100,000", "2 allocations"]];
  return <ReturnPageFrame title="Tax summary" subtitle="Known subtotals for calculation run CALC-000123 · revision 26." action={<button className="button secondary">View Form 1040</button>}>
    <div className="calculation-banner"><AlertCircle size={16} /><div><strong>Partial calculation · stale</strong><span>This run predates revision 28 and excludes unresolved Schedule E rental treatment. Refund or amount due is intentionally unavailable.</span></div></div>
    <div className="screen-grid-main"><section className="panel calculation-panel"><div className="calc-section"><h2>Income</h2>{lines.map(([label, amount, source]) => <button className="calc-line" key={label}><span><strong>{label}</strong><small>{source}</small></span><b>{amount}</b><ArrowRight size={14} /></button>)}<div className="calc-line total"><span><strong>Known income subtotal</strong><small>Excludes unsupported or unresolved amounts</small></span><b>$243,000</b><span /></div></div><div className="calc-section unavailable"><h2>Adjusted gross income</h2><p><AlertCircle size={15} /> Unavailable until Schedule E treatment, intake dependencies, and current calculation complete.</p></div><div className="calc-section unavailable"><h2>Tax, payments, refund / amount due</h2><p><AlertCircle size={15} /> Final totals are hidden because omitted facts can change the result.</p></div></section>
      <aside className="side-stack"><section className="panel compact-panel"><h2>Run manifest</h2><dl className="manifest"><div><dt>Run ID</dt><dd>CALC-000123</dd></div><div><dt>Input revision</dt><dd>26</dd></div><div><dt>Current revision</dt><dd>28</dd></div><div><dt>Engine</dt><dd>2025 rules pending approval</dd></div><div><dt>Required forms</dt><dd>7 · 1 unsupported</dd></div></dl></section><section className="panel compact-panel"><h2>Missing dependency</h2><p>Schedule E is required for $12,000 in mapped rent. The source is preserved, but calculation support is unavailable.</p></section></aside>
    </div>
  </ReturnPageFrame>;
}

export function ImportWizardScreen() {
  const [step, setStep] = useState(1);
  const labels = ["File", "Structure", "Tax data", "Change preview", "Commit"];
  return <div className="import-page"><header><Link href="/dashboard"><ArrowLeft size={14} /> Back to workspace</Link><div><FileJson size={22} /><span><strong>Import canonical JSON</strong><small>Safe staged import · no silent overwrite</small></span></div></header><ol className="wizard-steps">{labels.map((label, index) => <li className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} key={label}><span>{step > index + 1 ? <Check size={13} /> : index + 1}</span><b>{label}</b></li>)}</ol><main className="wizard-card">{step === 1 ? <><div className="drop-zone"><Upload size={28} /><h1>Upload canonical tax JSON</h1><p>Maximum 10 MiB · JSON only · no source files are transmitted externally</p><button className="button primary" onClick={() => setStep(2)}>Select synthetic sample</button></div><div className="wizard-note"><ShieldText /><p>Imported instructions and text are treated as data. They cannot execute tools, grant permissions, or approve a return.</p></div></> : <WizardStep step={step} />}</main><footer className="wizard-footer"><button className="button secondary" disabled={step === 1} onClick={() => setStep((current) => Math.max(1, current - 1))}>Previous</button><span>Changes remain staged until Commit.</span><button className="button primary" disabled={step === 5} onClick={() => setStep((current) => Math.min(5, current + 1))}>{step === 4 ? "Commit accepted changes" : "Continue"} <ArrowRight size={14} /></button></footer></div>;
}

function WizardStep({ step }: { step: number }) {
  if (step === 2) return <><h1>Structural validation</h1><p className="wizard-subtitle">completed-sample.json · Schema 1.0.0 · Tax year 2025 · Client 000123</p><ValidationList items={["Valid UTF-8 JSON", "Supported schema major version", "Required root objects present", "Record identities are unique", "Tax year and return type match"]} /></>;
  if (step === 3) return <><h1>Tax data validation</h1><p className="wizard-subtitle">18 records checked · 2 warnings · 0 rejected</p><ValidationList items={["TIN values have supported formats", "All source records have ownership", "One possible document duplicate requires review", "One low-confidence field remains unverified", "Unsupported rental treatment will create a blocker"]} warningFrom={2} /></>;
  if (step === 4) return <><h1>Change preview</h1><p className="wizard-subtitle">Each proposed change requires an explicit decision.</p><table className="change-table"><thead><tr><th>Record / field</th><th>Existing</th><th>Imported</th><th>Decision</th></tr></thead><tbody>{[["W-2 #2 · Box 14 UT SDI", "$300.00", "$321.10"], ["1099-INT #3 · Interest", "$980.00", "$1,000.00"], ["Intake · investment sales", "Unknown", "No"]].map((row, index) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td><select defaultValue={index === 2 ? "review" : "imported"}><option value="imported">Use imported</option><option value="existing">Keep existing</option><option value="review">Review later</option></select></td></tr>)}</tbody></table></>;
  return <><div className="commit-result"><CheckCircle2 size={36} /><h1>Import committed</h1><p>IMP-00042 · Revision 28</p></div><div className="commit-metrics"><div><strong>13</strong><span>Added</span></div><div><strong>2</strong><span>Updated</span></div><div><strong>1</strong><span>Review later</span></div><div><strong>3</strong><span>Review points</span></div><div><strong>0</strong><span>Rejected</span></div></div></>;
}

function ValidationList({ items, warningFrom = 99 }: { items: string[]; warningFrom?: number }) { return <div className="validation-list">{items.map((item, index) => <div key={item}>{index >= warningFrom ? <AlertCircle className="warning" size={16} /> : <CheckCircle2 size={16} />}<span>{item}</span><b>{index >= warningFrom ? "Review" : "Passed"}</b></div>)}</div>; }
function ShieldText() { return <LockKeyhole size={18} />; }

export function OutputsScreen() {
  return <div className="simple-page"><div className="page-header"><div><p className="eyebrow">Outputs</p><h1>Workpapers & return packages</h1><p>Every artifact is tied to an immutable input revision and calculation run.</p></div><button className="button primary" disabled>Generate current package</button></div><section className="panel"><table><thead><tr><th>Artifact</th><th>Type</th><th>Input revision</th><th>Calculation</th><th>Status</th><th>Generated</th><th>Action</th></tr></thead><tbody><tr><td><FileSpreadsheet size={15} /> 2025_John_Sample_Workpaper.xlsx</td><td>XLSX</td><td>26</td><td>CALC-000123</td><td><span className="stale-badge">Stale</span></td><td>Oct 6 · 9:15 AM</td><td><button className="text-action">View manifest</button></td></tr><tr><td><FileJson size={15} /> Complete canonical export</td><td>JSON</td><td>28</td><td>—</td><td><span className="success-badge">Current</span></td><td>Oct 6 · 9:46 AM</td><td><button className="text-action">Export</button></td></tr></tbody></table></section></div>;
}

export function IntegrationsScreen() {
  return <div className="simple-page"><div className="page-header"><div><p className="eyebrow">Capability matrix</p><h1>Tax software integrations</h1><p>Canonical data remains vendor-independent. No live vendor operation is available in Phase 1.</p></div></div><div className="integration-cards"><article><Link2 size={22} /><h2>Internal tax engine</h2><span className="success-badge">Foundation active</span><p>Calculation capabilities remain gated by approved 2025 rules and fixtures.</p></article><article><Link2 size={22} /><h2>CCH Axcess</h2><span className="planned-badge">Planned</span><p>Adapter contract only. Vendor access and supported operations are unverified.</p></article><article><Link2 size={22} /><h2>Drake Tax</h2><span className="planned-badge">Planned</span><p>Adapter contract only. No API, transfer, or proprietary-file capability is assumed.</p></article></div></div>;
}
