"use client";
import { AlertCircle,ArrowLeft,CheckCircle2,Database,Save } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo,useState } from "react";
import { formRegistries2025,readPath,registryFieldPath,type RegistryField } from "@/form-registry/2025";
interface RecordRow{id:string;sourceFileName:string|null;formType:string;externalSourceId:string|null;ownerRole:string;normalizedData:Record<string,unknown>;rawFieldCount:number;unmappedFieldCount:number;effective:boolean;disposition:string;version:number}
interface State{revision:number;records:RecordRow[]}
export function RegistrySourceEntry({clientId,year,clientName,initial}:{clientId:string;year:number;clientName:string;initial:State}){const router=useRouter();const records=useMemo(()=>initial.records.filter(record=>record.effective&&["original","corrected"].includes(record.disposition)&&formRegistries2025[record.formType]),[initial.records]);const[selectedId,setSelectedId]=useState(records[0]?.id??"");const selected=records.find(record=>record.id===selectedId)??records[0];const registry=selected?formRegistries2025[selected.formType]:null;const[values,setValues]=useState<Record<string,string>>(()=>selected&&registry?valuesFor(selected,registry.fields):{});const[reason,setReason]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);function select(record:RecordRow){setSelectedId(record.id);const definition=formRegistries2025[record.formType];setValues(valuesFor(record,definition.fields));setReason("");setError(null);}async function save(){if(!selected||!registry)return;let data:Record<string,unknown>=structuredClone(selected.normalizedData);try{for(const field of registry.fields){const raw=values[field.key]??"";let value:unknown=null;if(field.type==="boolean")value=raw===""?null:raw==="true";else if(field.type.startsWith("repeatable_")||field.type==="checkbox_group"){value=raw.trim()?JSON.parse(raw):field.type==="checkbox_group"?{}:[];if(field.type.startsWith("repeatable_")&&!Array.isArray(value))throw new Error(`${field.label} must be a JSON array.`);if(field.type==="checkbox_group"&&(!value||typeof value!=="object"||Array.isArray(value)))throw new Error(`${field.label} must be a JSON object.`);}else value=raw.trim()||null;data=writePath(data,registryFieldPath(selected.formType,field.key),value);}}catch(caught){setError(caught instanceof Error?caught.message:"A repeatable field contains invalid JSON.");return;}setSaving(true);setError(null);const response=await fetch(`/api/clients/${clientId}/years/${year}/source-records/${selected.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedRevision:initial.revision,expectedVersion:selected.version,action:"correct",reason,normalizedData:data})});const body=await response.json();setSaving(false);if(!response.ok){setError(body.message??body.error??"Source record save failed.");return;}router.refresh();}
return <div className="return-page registry-entry-page"><div className="return-page-top"><Link href={`/clients/${clientId}/years/${year}`}><ArrowLeft size={14}/> {clientName} · {year}</Link><span>Revision {initial.revision}</span><b>2025 registry v2025.1.0</b></div><header><div><p>SOURCE ENTRY · YEAR-VERSIONED REGISTRY</p><h1>W-2 and information-return fields</h1><span>All registered fields are captured even when calculation treatment is conditional or future. Saving creates an immutable corrected version.</span></div><button className="button primary" disabled={!selected||saving||!reason.trim()} onClick={save}><Save size={13}/>{saving?"Saving…":"Save correction"}</button></header>{error?<p className="form-error" role="alert">{error}</p>:null}<div className="registry-entry-layout"><aside className="panel registry-record-list"><div className="panel-heading"><div><h2>Effective records</h2><p>{records.length} supported source forms</p></div></div>{records.map(record=><button className={record.id===selected?.id?"active":""} key={record.id} onClick={()=>select(record)}><Database size={14}/><span><b>{record.formType} · {issuer(record)}</b><small>{record.ownerRole} · v{record.version} · {record.sourceFileName??"no attached original"}</small></span>{record.unmappedFieldCount?<AlertCircle size={13}/>:<CheckCircle2 size={13}/>}</button>)}</aside><main className="panel registry-fields">{selected&&registry?<><div className="panel-heading"><div><h2>{selected.formType} · version {selected.version}</h2><p>{registry.fields.length} year-defined fields · raw {selected.rawFieldCount} · unmapped {selected.unmappedFieldCount}</p></div><span className="registry-support">PDF {registry.pdf_output.replaceAll("_"," ")}</span></div><div className="registry-field-grid">{registry.fields.map(field=><RegistryControl key={field.key} field={field} value={values[field.key]??""} onChange={value=>setValues(current=>({...current,[field.key]:value}))}/>)}</div><label className="registry-reason"><span>Correction reason and evidence</span><input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Required; explain what changed and identify the source evidence"/></label></>:<p className="empty-panel">No effective W-2 or supported 1099 source records are available.</p>}</main></div></div>}
function RegistryControl({field,value,onChange}:{field:RegistryField;value:string;onChange:(value:string)=>void}){const structured=field.type.startsWith("repeatable_")||field.type==="checkbox_group";return <label className={structured?"registry-structured":""}><span>{field.label}<small className={`support-${field.calculation}`}>{field.calculation.replaceAll("_"," ")}</small></span>{field.type==="boolean"?<select value={value} onChange={event=>onChange(event.target.value)}><option value="">Blank / unknown</option><option value="true">Yes</option><option value="false">No</option></select>:structured?<textarea value={value} onChange={event=>onChange(event.target.value)} spellCheck={false}/>:<input inputMode={field.type==="money"?"decimal":"text"} value={value} onChange={event=>onChange(event.target.value)} placeholder={field.type==="money"?"0.00":""}/>}</label>}
function valuesFor(record:RecordRow,fields:RegistryField[]){return Object.fromEntries(fields.map(field=>{const value=readPath(record.normalizedData,registryFieldPath(record.formType,field.key));return[field.key,value===undefined||value===null?"":typeof value==="object"?JSON.stringify(value,null,2):String(value)];}));}
function writePath(root:Record<string,unknown>,path:string[],value:unknown){const copy=structuredClone(root);let cursor=copy;for(const key of path.slice(0,-1)){const next=cursor[key];if(!next||typeof next!=="object"||Array.isArray(next))cursor[key]={};cursor=cursor[key] as Record<string,unknown>;}cursor[path.at(-1)!]=value;return copy;}
function issuer(record:RecordRow){const data=record.normalizedData;const payer=data.payer&&typeof data.payer==="object"&&!Array.isArray(data.payer)?(data.payer as Record<string,unknown>).name:null;const employer=data.employer&&typeof data.employer==="object"&&!Array.isArray(data.employer)?(data.employer as Record<string,unknown>).name:null;return typeof payer==="string"?payer:typeof employer==="string"?employer:"Unnamed issuer";}
