"use client";

import { Archive, LockKeyhole, Save, ShieldAlert, Trash2, UnlockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Category = "source_originals" | "import_payloads" | "calculation_snapshots" | "generated_artifacts" | "audit_history" | "backups";
type Disposition = "review" | "archive" | "delete";
interface Policy { category: Category; retentionMonths: number; disposition: Disposition; policyBasis: string; version: number; updatedAt: string; updatedBy: string }
interface Hold { id: string; taxYearId: string | null; clientCode: string; taxYear: number | null; reference: string; reason: string; placedAt: string; placedBy: string; releasedAt: string | null; releaseReason: string | null; releasedBy: string | null; version: number }
interface Scope { taxYearId: string; clientId: string; clientCode: string; taxYear: number }
interface DisposalRun { id: string; category: Category; cutoffAt: string; authorizationReference: string; candidateCount: number; disposedCount: number; heldCount: number; skippedCount: number; evidenceHash: string; executedAt: string; executedBy: string }
interface DisposalPreview { category: Category; cutoffAt: string; policyVersion: number; candidateCount: number; disposedCount: number; heldCount: number; skippedCount: number; batchLimit: number }
interface State { canManage: boolean; policies: Policy[]; holds: Hold[]; scopes: Scope[]; disposalRuns: DisposalRun[] }

const categories: Category[] = ["source_originals", "import_payloads", "calculation_snapshots", "generated_artifacts", "audit_history", "backups"];
const disposableCategories: Category[] = ["source_originals", "import_payloads", "calculation_snapshots", "generated_artifacts"];
const labels: Record<Category, string> = { source_originals: "Source originals", import_payloads: "Import payloads", calculation_snapshots: "Calculation snapshots", generated_artifacts: "Generated artifacts", audit_history: "Audit history", backups: "Backups" };

export function RetentionAdministration({ initial }: { initial: State }) {
  const router = useRouter();
  const [editing, setEditing] = useState<Policy | { category: Category; retentionMonths: number; disposition: Disposition; policyBasis: string; version: null } | null>(null);
  const [holdScope, setHoldScope] = useState(initial.scopes[0]?.taxYearId ?? "");
  const [holdReference, setHoldReference] = useState("");
  const [holdReason, setHoldReason] = useState("");
  const [releaseTarget, setReleaseTarget] = useState<Hold | null>(null);
  const [releaseReason, setReleaseReason] = useState("");
  const [disposalPreview, setDisposalPreview] = useState<DisposalPreview | null>(null);
  const [disposalReference, setDisposalReference] = useState("");
  const [disposalConfirmation, setDisposalConfirmation] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!initial.canManage) return <><div className="page-header"><div><p className="eyebrow">ADMINISTRATION</p><h1>Firm governance</h1><p>Retention policy and legal holds are restricted to administrators.</p></div></div><section className="panel access-restricted"><ShieldAlert size={20}/><div><h2>Administrator permission required</h2><p>Your current firm role cannot view or change retention governance.</p></div></section></>;

  async function mutate(body: Record<string, unknown>) {
    setSaving(true); setError(null);
    const response = await fetch("/api/administration/retention", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json();
    setSaving(false);
    if (!response.ok) { setError(result.message ?? result.error ?? "Retention update failed."); return null; }
    router.refresh();
    return result;
  }

  async function savePolicy() { if (editing && await mutate({ operation: "save_policy", category: editing.category, retentionMonths: editing.retentionMonths, disposition: editing.disposition, policyBasis: editing.policyBasis, expectedVersion: editing.version })) setEditing(null); }
  async function placeHold() { if (await mutate({ operation: "place_hold", taxYearId: holdScope, reference: holdReference, reason: holdReason })) { setHoldReference(""); setHoldReason(""); } }
  async function releaseHold() { if (releaseTarget && await mutate({ operation: "release_hold", holdId: releaseTarget.id, expectedVersion: releaseTarget.version, reason: releaseReason })) { setReleaseTarget(null); setReleaseReason(""); } }
  async function previewDisposal(category: Category) { const result = await mutate({ operation: "preview_disposal", category }); if (result) { setDisposalPreview(result as DisposalPreview); setDisposalReference(""); setDisposalConfirmation(""); } }
  async function executeDisposal() { if (disposalPreview && await mutate({ operation: "execute_disposal", category: disposalPreview.category, expectedPolicyVersion: disposalPreview.policyVersion, previewCutoffAt: disposalPreview.cutoffAt, authorizationReference: disposalReference, confirmation: disposalConfirmation })) { setDisposalPreview(null); setDisposalReference(""); setDisposalConfirmation(""); } }

  return <>
    <div className="page-header"><div><p className="eyebrow">ADMINISTRATION · DATA GOVERNANCE</p><h1>Retention policy and legal holds</h1><p>Firm-approved periods are configurable; active holds transactionally block disposal.</p></div></div>
    {error ? <p className="form-error" role="alert">{error}</p> : null}
    <section className="panel retention-policies"><div className="panel-heading"><div><h2>Retention schedule</h2><p>No universal period is assumed. Record the firm-approved basis for every data category.</p></div></div>{categories.map((category) => { const policy = initial.policies.find((item) => item.category === category); return <article key={category}><Archive size={15}/><div><b>{labels[category]}</b><small>{policy ? `${policy.retentionMonths} months · ${policy.disposition} after period` : "Not configured — production gate remains blocked"}</small>{policy ? <small>v{policy.version} · {policy.updatedBy} · {new Date(policy.updatedAt).toLocaleString()}</small> : null}</div><p>{policy?.policyBasis ?? "An administrator must document the applicable legal and operating basis."}</p><div className="retention-actions"><button className="button secondary" onClick={() => setEditing(policy ?? { category, retentionMonths: 0, disposition: "review", policyBasis: "", version: null })}>{policy ? "Edit" : "Configure"}</button>{policy?.disposition === "delete" && disposableCategories.includes(category) ? <button className="button secondary" disabled={saving} onClick={() => previewDisposal(category)}><Trash2 size={12}/>Preview</button> : null}</div></article>; })}</section>
    {editing ? <section className="panel retention-editor"><div><h2>{labels[editing.category]}</h2><p>Changes use optimistic version checks and append a tax-value-free audit event.</p></div><label><span>Retention months</span><input type="number" min={1} max={1200} value={editing.retentionMonths || ""} onChange={(event) => setEditing({ ...editing, retentionMonths: Number(event.target.value) })} placeholder="Firm-approved period"/></label><label><span>End-of-period action</span><select value={editing.disposition} onChange={(event) => setEditing({ ...editing, disposition: event.target.value as Disposition })}><option value="review">Review</option><option value="archive">Archive</option><option value="delete">Authorized deletion review</option></select></label><label className="retention-basis"><span>Policy basis</span><textarea maxLength={2000} value={editing.policyBasis} onChange={(event) => setEditing({ ...editing, policyBasis: event.target.value })} placeholder="Approved legal, regulatory, contractual, and operating rationale"/></label><div><button className="button secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button primary" disabled={saving || editing.retentionMonths < 1 || !editing.policyBasis.trim()} onClick={savePolicy}><Save size={13}/>{saving ? "Saving…" : "Save policy"}</button></div></section> : null}
    {disposalPreview ? <section className="panel disposal-preview"><div><h2>Disposal preview · {labels[disposalPreview.category]}</h2><p>Cutoff {new Date(disposalPreview.cutoffAt).toLocaleString()} · policy v{disposalPreview.policyVersion}. Execution rechecks active holds inside the transaction.</p><div className="disposal-counts"><b>{disposalPreview.disposedCount} eligible</b><b>{disposalPreview.heldCount} held</b><b>{disposalPreview.skippedCount} skipped</b><small>Maximum {disposalPreview.batchLimit} records per run</small></div></div><label><span>Authorization reference</span><input maxLength={200} value={disposalReference} onChange={(event) => setDisposalReference(event.target.value)} placeholder="Approved ticket or decision reference"/></label><label><span>Type DELETE {disposalPreview.category}</span><input value={disposalConfirmation} onChange={(event) => setDisposalConfirmation(event.target.value)} autoComplete="off"/></label><div><button className="button secondary" onClick={() => setDisposalPreview(null)}>Cancel</button><button className="button primary" disabled={saving || !disposalReference.trim() || disposalConfirmation !== `DELETE ${disposalPreview.category}`} onClick={executeDisposal}><Trash2 size={13}/>{saving ? "Executing…" : "Execute disposal"}</button></div></section> : null}
    <section className="panel legal-holds"><div className="panel-heading"><div><h2>Legal holds</h2><p>Active holds supersede configured archive or deletion actions for their client and tax-year scope.</p></div></div><div className="legal-hold-create"><label><span>Tax-year scope</span><select value={holdScope} onChange={(event) => setHoldScope(event.target.value)}>{initial.scopes.map((scope) => <option value={scope.taxYearId} key={scope.taxYearId}>{scope.clientCode} · {scope.taxYear}</option>)}</select></label><label><span>Hold reference</span><input value={holdReference} maxLength={200} onChange={(event) => setHoldReference(event.target.value)} placeholder="Matter or authorization reference"/></label><label><span>Reason</span><input value={holdReason} maxLength={2000} onChange={(event) => setHoldReason(event.target.value)} placeholder="Reason records must be preserved"/></label><button className="button primary" disabled={saving || !holdScope || !holdReference.trim() || !holdReason.trim()} onClick={placeHold}><LockKeyhole size={13}/>Place hold</button></div>{initial.holds.map((hold) => <article key={hold.id} className={hold.releasedAt ? "released" : "active"}><LockKeyhole size={15}/><div><b>{hold.clientCode} · {hold.taxYear ?? "all years"} · {hold.reference}</b><small>{hold.reason}</small></div><div><strong>{hold.releasedAt ? "Released" : "Active hold"}</strong><small>Placed {new Date(hold.placedAt).toLocaleString()} by {hold.placedBy}</small>{hold.releasedAt ? <small>Released by {hold.releasedBy}: {hold.releaseReason}</small> : null}</div>{!hold.releasedAt ? <button className="button secondary" onClick={() => { setReleaseTarget(hold); setReleaseReason(""); }}><UnlockKeyhole size={13}/>Release</button> : null}</article>)}</section>
    {releaseTarget ? <section className="panel hold-release"><div><h2>Release {releaseTarget.reference}</h2><p>The historical hold remains visible and audited.</p></div><label><span>Release reason</span><input maxLength={2000} value={releaseReason} onChange={(event) => setReleaseReason(event.target.value)}/></label><div><button className="button secondary" onClick={() => setReleaseTarget(null)}>Cancel</button><button className="button primary" disabled={saving || !releaseReason.trim()} onClick={releaseHold}>Release hold</button></div></section> : null}
    <section className="panel disposal-history"><div className="panel-heading"><div><h2>Disposal evidence</h2><p>Receipts and item outcomes are immutable; hashes contain no tax values.</p></div></div>{initial.disposalRuns.length ? initial.disposalRuns.map((run) => <article key={run.id}><Trash2 size={15}/><div><b>{labels[run.category]} · {run.authorizationReference}</b><small>{new Date(run.executedAt).toLocaleString()} by {run.executedBy} · cutoff {new Date(run.cutoffAt).toLocaleDateString()}</small></div><div><b>{run.disposedCount} disposed · {run.heldCount} held · {run.skippedCount} skipped</b><small>Evidence {run.evidenceHash.slice(0, 16)}…</small></div></article>) : <p className="empty-note">No disposal has been executed.</p>}</section>
  </>;
}
